[package]
name = "status_server"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99"
tokio = { version = "1.32", features = ["macros", "net", "rt", "rt-multi-thread", "io-util"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
assert_matches = "1.5"
